version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    networks:
      - nginx_network
      - database1_network
      - database2_network
    environment:
      - DJANGO_SETTINGS_MODULE
    depends_on:
      - database1
      - database2
  nginx:
    image: nginx:1.13
    ports:
      - 8000:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static:/opt/services/djangoapp/static
      - media:/opt/services/djangoapp/media
    depends_on:  # <-- wait for djangoapp to be "ready" before starting this service
      - djangoapp
    networks:
      - nginx_network
  database2:
    image: postgres:10
    env_file: 
      - config/db/database2_env
    networks:
      - database2_network
    volumes:
      - database2_volume:/var/lib/postgresql/data
  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data
networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge
  database2_network:
    driver: bridge
volumes:
  database1_volume:
  database2_volume:
  static:
  media:
  