# Generated by Django 2.1.4 on 2018-12-05 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lnkfrm', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlink',
            name='user',
        ),
        migrations.AddField(
            model_name='userlink',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
