FROM ubuntu:16.04
MAINTAINER code-machina <gbkim1988@gmail.com>

# 업데이트 필수
RUN apt-get update
# 필수 패키지 설치
RUN apt-get install -y -qq gcc g++ make python3=3.5.1* autoconf wget build-essential p7zip-full python3-pip python python-pip sudo
# 디렉터리 생성
RUN mkdir /data /data/tool /app /app/shred
# 디렉터리 이동
WORKDIR /data/tool 
# wmi-1.3.15-patched.7z 다운로드
RUN wget https://github.com/code-machina/awesome-packages/raw/master/openvas-wmi/wmi-1.3.14-patched.7z
# 7z 압축 파일 해제
RUN 7z x ./wmi-1.3.14-patched.7z 
# 디렉터리 이동
WORKDIR /data/tool/wmi-1.3.14
# 빌드하기
RUN chmod -R +x ./
RUN sudo make "CPP=gcc -E -ffreestanding"
# 실행 파일 복사
RUN sudo cp Samba/source/bin/wmic /usr/local/bin/
# python3 모듈 설치
RUN pip3 install wmi-client-wrapper

COPY mango /app/shred
COPY requirements-181116.txt /app/shred
WORKDIR /app/shred/
RUN pip3 install -r ./requirements-181116.txt

EXPOSE 80
EXPOSE 443